### ISSUE TITLE
Investigate - Developing inside a Container

### ISSUE THREAD

**Issue by kevinhillinger** [ansible/azure-aap-deployment-driver#16]
## Description
To reduce the amount of developer friction across different OSs, investigate using [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers) setup to solve for this. This would only offer direct integration in VSCode, however.

## Proof
- setup .devcontainer
- Show all dev commands working (in the Makefile)
- Demonstrate successfully starting all processes inside the dev container 
- Be able to launch the UI in a browser running in the host OS

## Demonstration
Provide a branch that implements .devcontainer in Linux container, providing comments in the issue with the pro/con list.

**Comment by bobjac** [comment]
I'll take a look at this one.

**Comment by bobjac** [comment]
Closing as pull request as been accepted
