### ISSUE TITLE
```make run``` - for local development start up

### ISSUE THREAD

**Issue by kevinhillinger** [ansible/azure-aap-deployment-driver#17]
## Description
There currently is no `one-click` start up for local development.

## Solution
- Add a ```run``` target to the root Makefile that will get the local development environment up and running for a developer.
- add a ```run-docker``` to target running everything in a docker container locally for manual, smoke testing post UI and server build
   - container is built
   - use docker-compose to launch on a docker network
   - expose the UI via pre-defined Host port
   - set all required input variables via *.env file (Dockerfile conditional copy)

### Implementation
It should perform the following:
- start ./ui project (with file watch)
- start server (at ./server/build)

**Comment by kevinmgates** [comment]
#27

**Comment by kevinhillinger** [comment]
closing this issue since Ansible avoids placing run statements in their make file.
