### ISSUE TITLE
Replace python-based API stub

### ISSUE THREAD

**Issue by kevinhillinger** [ansible/azure-aap-deployment-driver#18]
## Problem
Currently, there's a python-based API stub that contains some hard coded results for the UI to work. This was to get around the backend server not being easily stood up due to many environment variables as "inputs" (the inputs problem and `server` startup is being solve in issue ansible/azure-aap-deployment-driver#21).

## Solution
Use backend `server` for running the solution and remove the sub. 

> The stubbed API primarily serves as a hard-coded result set for the `/step` path which is registered, [here](https://github.com/ansible/azure-aap-deployment-driver/blob/39376f5ea9a043a43858184a73feeb552d99263d/server/api/installer.go#L77), in `server`.

The implementation will need to have the following elements:

- Support runtime environment values: development | production
- Delete the API stub found in `./ui` in favor of using `server`, whether in development or production
- Migrate all stubbed test data hard coded in ```./ui/run.py``` into `./server`

## Implementation
- Add an additional environment variable of `APP_ENV`. See [`server/config/environment.go`](https://github.com/ansible/azure-aap-deployment-driver/blob/main/server/config/environment.go) on examples of reading in a value using the _go-envs_ library

### Runtime Environment - development | production
To support defining a runtime environment, an environment variable is introduced.

- Modify `server/config/environment.go`, adding `ENVIRONMENT_NAME` to `envVars`. 
   - Valid values are: development | production
   - Default value: __production__ (this is to avoid breaking changes since we're adding another execution path if `development`)
- environment variable `ENVIRONMENT_NAME`
- Support setting of a [flag](https://www.digitalocean.com/community/tutorials/how-to-use-the-flag-package-in-go) `-environment`
   - Example: `./server -environment development' 
   - If flag value is present, it should override any environment variable set, otherwise, default to environment variable value 

### Seed data
Using the structs defined in [server/model/model.go](https://github.com/ansible/azure-aap-deployment-driver/blob/main/server/model/model.go), add an additional file to the model package, `seed_development.go`. Here, translate what's in the python stub API as hard-coded JSON / string literal into Go code. Have a "public" (to the package) function that accepts a `*persistence.Database` as an argument, seeding that instance with data.

> The function defined in seed_development.go will be used in `main` depending on the runtime environment.

### Startup changes
Modify [`server/main.go`](https://github.com/ansible/azure-aap-deployment-driver/blob/main/server/main.go) with a private function `getDatabase` that replaces the call being used to just new up a database. The gist of this function's body is  conditional checking of the environment to determine whether to start up:
- development: an in memory database and seed it
- production: call and return the same call that's there now to get a new database

### Deletion of the python API
Once the changes to the `server` are implemented, the full removal of the Python API will still need to wait until the `server` can start up easily, which will be completed in issue ansible/azure-aap-deployment-driver#21.

**Comment by kevinhillinger** [comment]
Whether to delete the stub API or not as part of this work, check with @kevinhillinger who is working on ansible/azure-aap-deployment-driver#21. If this work hasn't been merged in, the stub API should remain temporarily.

**Comment by kevinmgates** [comment]
Thanks for the detailed write-up. Reviewing now.

> Whether to delete the stub API or not as part of this work, check with @kevinhillinger who is working on #21. If this work hasn't been merged in, the stub API should remain temporarily.

Makes sense!

**Comment by kevinmgates** [comment]
Completed the runtime flag: https://github.com/kevinmgates/azure-aap-deployment-driver/commit/ad333023767b2624e82684ade80c2de752e1621c

**Comment by kevinhillinger** [comment]
Closing. @bobjac created script and provided offline from the repo, first week of may
